---
apiVersion: v1
kind: ConfigMap
metadata:
  name: my-configmap
data:
  default.conf: |
    server {
        listen       80 default_server;
        server_name  _;

        default_type text/plain;

        location / {
            return 200 '$hostname\n';
        }
    }

...

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-nginx-deploy
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx    
    spec:
      containers:
      - name: test-cont
        image: automation.azurecr.io/nginx-1-19-1-qa-agent-team:251020221006
        env:
        - name: __NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: __POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: __POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: __POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: __NODE_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: __POD_SERVICE_ACCOUNT
          valueFrom:
            fieldRef:
              fieldPath: spec.serviceAccountName
        ports:
        - containerPort: 80
        volumeMounts:
        - name: config
          mountPath: /etc/nginx/conf.d/
        - mountPath: /tmp/aqua/dirA
          name: mount-test-1
        - mountPath: /tmp/aqua/dirB
          name: mount-test-2  
      volumes:
      - name: config
        configMap:
          name: my-configmap
      - name: mount-test-1
        hostPath:
          path: /tmp/A
      - name: mount-test-2
        hostPath:
          path: /tmp/B    
      imagePullSecrets:
      - name: regcred-acr
...